version: '3.3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: alendre_dasneuner_regularization
    volumes:
      - .:/var/www/html/
    ports:
      - 8003:80
